config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index,:edit,:update] 
 
  resources :guitars do
     resource :favorites, only: [:create, :destroy]
     resources :_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :guitar
end

app/models/guitar.rb
class Guitar < ApplicationRecord
  belongs_to :user
	
	has_many :favorites
	 has_many :guitar_comments
	
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/guitar_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :guitar

	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :guitars
  has_many :favorites
  has_many :guitar_comments

  attachment :profile_image, destroy: false

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    guitar = Guitar.find(params[:guitar_id])
    favorite = current_user.favorites.new(guitar_id: guitar.id)
    favorite.save
    redirect_back(fallback_location: guitars_path)
  end
  
  def destroy
    guitar = Guitar.find(params[:guitar_id])
    favorite = current_user.favorites.find_by(guitar_id: guitar.id)
    favorite.destroy
    redirect_back(fallback_location: guitars_path)
  end
  
end

app/controllers/guitar_comments_controller.rb
class GuitarCommentsController < ApplicationController
  def create
    guitar = Guitar.find(params[:guitar_id])
    comment = current_user.guitar_comments.new(guitar_comment_params)
    comment.guitar_id = guitar.id
   if comment.save
     redirect_back(fallback_location: guitars_path)
 　else
　   redirect_back(fallback_location: guitars_path)
　 end
  end

  def destroy
    GuitarComment.find_by(id: params[:id], guitar_id: params[:guitar_id]).destroy
    redirect_back(fallback_location: guitars_path)
  end

	private
	def guitar_comment_params
		params.require(:guitar_comment).permit(:comment)
	end
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

  def show
    @guitar_new = Guitar.new
    @guitar = Guitar.find(params[:id])
    @user = @guitar.user
    @guitar_comment = GuitarComment.new
    
  end

  def index
    @user = current_user
    @guitars = Guitar.all
    @guitar = Guitar.new
  end

 def create
    @user = current_user
    @guitar = Guitar.new(guitar_params)
    @guitar.user_id = (current_user.id)
  if @guitar.save
    flash[:notice] = "You have creatad guitar successfully."
     @guitars = Guitar.all
     redirect_to "/guitars/#{@guitar.id}"
  else
     @guitars = Guitar.all
     flash[:notice] = ' errors prohibited this obj from being saved:'
     render "index"
  end
 end

  def edit
    @guitar = Guitar.find(params[:id])
  end

  def update
    @guitar = Guitar.find(params[:id])
    if @guitar.update(guitar_params)
      redirect_to guitar_path(@guitar), notice: "You have updated guitar successfully."
    else
      @guitars = Guitar.all
      render "edit"
    end
  end

  def destroy
    @guitar = Guitar.find(params[:id])
    @guitar.destroy
    redirect_to guitars_path
  end

  private

  def guitar_params
    params.require(:guitar).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
  
  def ensure_current_user
      @guitar = Guitar.find(params[:id])
   if @guitar.user_id != current_user.id
      redirect_to guitars_path
   end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit,:update,:destroy]}

  def show
    @guitar = Guitar.new
    @user = User.find(params[:id])
    @guitars = @user.guitars
  end

  def index
    @users = User.all
    @guitar = Guitar.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to "/users/#{current_user.id}"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/guitar_comments_helper.rb
module GuitarCommentsHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/guitars/_comments.html.erb
<% if guitar.favorited_by?(current_user) %>
             <td>
             
              <%= link_to guitar_favorites_path(guitar), method: :delete do %>
               <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
               <%= guitar.favorites.count %> いいね
              <% end %>
             
             </td>
             <% else %>
             
             <td>
              <%= link_to guitar_favorites_path(guitar), method: :post do %>
               <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
               <%= guitar.favorites.count %> いいね
              <% end %>
             
             </td>
            <% end %>	

app/views/guitars/_favorites.html.erb
<div class="comment-list bt style-2" id="comments">
            
<ol>
  <% guitar.guitar_comments.each do |guitar_comment| %>
    <li class="comment">
      <div class="comment-body bb">
        <div class="comment-avatar">
          <div class="avatar">
           <%= attachment_image_tag guitar_comment.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
          </div>
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <a href="#" class="link-author"><%= guitar_comment.user.name %></a>
            <span class="comment-meta">
              <span class="comment-date"><%= guitar_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry"><%= guitar_comment.comment %></div>
          <% if guitar_comment.user == current_user %>
            <div>
              <%= link_to "削除", guitar_guitar_comment_path(guitar_comment.guitar, guitar_comment), method: :delete, class: "btn btn-danger pull-right" %>
            </div>
          <% end %>

        </div>
      </div>
    </li>
  <% end %>
</ol>
          </div>
          <hr>

          <!-- comment section -->
          <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
            <h3 class="section-title left">
              <span>コメント</span>
            </h3>
          </div>
          <%= form_with(model:[guitar, guitar_comment], local: true) do |f| %>
            <div class="row">
              <div class="col-sm-12">
                <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
              </div>
            </div>
            <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
          <% end %>

app/views/guitars/_form.html.erb
<%= form_with model:guitar,local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 guitar_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 guitar_body'%>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/guitars/_index.html.erb
<table class='table table-hover table-inverse'>
 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% guitars.each do |guitar| %>
      <tr>
        <td><%= link_to user_path(guitar.user) do %>
          <%= attachment_image_tag(guitar.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to guitar.title, guitar_path(guitar), class: "guitar_#{guitar.id}" %></td>
        <td><%= guitar.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/guitars/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Guitar</h1>

		<%= render "guitars/form", guitar: @guitar %>
		<%= link_to "Show", guitar_path(@guitar), class: "guitar_#{@guitar.id}" %>
		|
		<%= link_to "Back", guitars_path, class: "back" %>

	<div class="error">
   <% if @guitar.errors.any? %>
   <div id="error_explanation" class="alert alert-danger error">
    <ul>
     error
     <% @guitar.errors.full_messages.each do |message| %>
      <li><%=message %></li>
      <% end %>
    </ul>
   </div>
   <% end %>
   </div>
   
	</div>
	<div class="col-md-3"></div>


</div>

app/views/guitars/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New guitar</h2>
		<%= render 'guitars/form', guitar: @guitar %>

  <div class="error">
   <% if @guitar.errors.any? %>
   <div id="error_explanation" class="alert alert-danger error">
    <ul>
     error
     <% @guitar.errors.full_messages.each do |message| %>
      <li><%=message %></li>
      <% end %>
    </ul>
   </div>
   <% end %>
   </div>


	</div>

	<div class="col-xs-9">
		<h2>GUitars index</h2>
		<!--guitars一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @guitars.each do |guitar| %>
				<tr>
					<td>
						<%= link_to user_path(guitar.user) do %>
							<%= attachment_image_tag(guitar.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to guitar.title, guitar_path(guitar), class: "guitar_#{guitar.id}" %></td>
					<td><%= guitar.body %></td>
					<%= render 'books/favorites', guitar: guitar%>
				    
				    
				    <td>
				     <ul class="inline-meta">
                        <%= link_to "コメント数　#{guitar.guitar_comments.count}", guitar_path(guitar.id) %>
                       </li>
                     </ul>
                    </td>
				    
				    
				</tr>
				<% end %>
	
            
			</tbody>
		</table>

		<!--guitars一覧 -->


	</div>
</div>

app/views/guitars/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New guitar</h2>
		<%= render 'guitars/form', guitar: @guitar_new %>

	</div>

	<div class="col-xs-9">
		<h2> detail</h2>
		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@guitar.user) do %>
							<%= attachment_image_tag(@guitar.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @guitar.user.name %>
						<% end %>
					</td>
					<td><%= link_to @guitar.title, guitar_path(@guitar) %></td>
					<td><%= @guitar.body %></td>
	
	        
               <%= render 'guitars/favorites', guitar: @guitar %>
               
             <td>
              <div class="comment-count">コメント数：<%= @guitar.guitar_comments.count %></div>
            </div>    
            </td>
            
            
              
        

	               <% if @guitar.user_id == current_user.id %>
					 <td><%= link_to "Edit", edit_guitar_path(@guitar), class: "btn-sm btn-success edit_guitar_#{@guitar.id}" %></td>
					 <td><%= link_to "Destroy", guitar_path(@guitar), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_guitar_#{@guitar.id}" %></td>
			       <% end %>
				</tr>
		</table>
		
	<%= render 'guitars/comments', guitar: @guitar, guitar_comment: @guitar_comment %>
		
	</div>
</div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-music"></span><strong>Whose Guitar</strong>!</h1>

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class="glyphicon glyphicon-music"></span><strong>Whose guitar</strong>  ?</h1>
    <p>In  <span class="glyphicon glyphicon-music"></span><strong>s</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various guitars!</p>
    

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Sasaki.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Whose guitar?</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Guitars', guitars_path, class: "glyphicon glyphicon-music"%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whose guitar?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
</table>

<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= render 'users/profile', user: current_user %>

    <h2>New guitar</h2>
    <%= render 'guitars/form', guitar: @guitar %>
  </div>
  
  <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table">
    	<thead>
	    	<tr>
		    	<th>image</th>
		    	<th>name</th>
			    <th colspan="3"></th>
	    	</tr>
    	</thead>

    	<tbody>
	    	<% @users.each do |user| %>
	    	<tr>
		    	<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
		    	<td><%= user.name %></td>
		    	<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
	    	</tr>
	    	<% end %>
    	</tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New guitar</h2>
		<%= render 'guitars/form', guitar: @guitar %>
	</div>

	<div class="col-xs-9">
		<h2>guitars</h2>
		
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @guitars.each do |guitar| %>
					<tr>
						<td>
							<%= link_to user_path(guitar.user) do %>
								<%= attachment_image_tag(guitar.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to guitar.title, guitar_path(guitar), class: "guitar_#{guitar.id}" %></td>
						<td><%= guitar.body %></td>
						
						<td>
              <div class="comment-count">コメント数：<%= guitar.guitar_comments.count %></div>
            </div>    
            </td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>